---
default:
  tags:
    - kubernetes

variables:
  HUGO_DOWNLOAD_URL: "https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_extended_0.92.1_Linux-64bit.tar.gz"

stages:
  - build
  - test
  - deploy

# Jobs
.build:s3:
  stage: build
  image: klakegg/hugo:ext-alpine
  before_script:
    - apk add --update-cache --upgrade curl p7zip
  script:
    - hugo version
    - hugo -b $HUGO_BASE_URL
    - ls -alh ./public/
    - 7z a $CI_PROJECT_DIR/site.7z $CI_PROJECT_DIR/public/*
  artifacts:
    paths:
      - $CI_PROJECT_DIR/site.7z
    expire_in: 1 hour

.deploy:s3:
  stage: deploy
  image: registry.coreinfra.cloud/hlv/dockerfiles/hlv-kubetools:latest
  script:
    - aws sts get-caller-identity
    - mkdir -p /tmp/$CI_PROJECT_NAME
    - 7z x -o/tmp/$CI_PROJECT_NAME site.7z &&
    - aws s3 sync /tmp/$CI_PROJECT_NAME/. s3://$AWS_S3_BUCKET/
  allow_failure: false

# Prod Build
build:s3:prod:
  extends: .build:s3
  environment:
    name: prod
    url: https://nicholas.santiago.wtf
  variables:
    HUGO_BASE_URL: "https://nicholas.santiago.wtf"
  only:
    - main

deploy:s3:prod:
  extends: .deploy:s3
  environment:
    name: prod
  needs:
    - job: build:s3:prod
      artifacts: true
  only:
    - main
