---
default:
  image: registry.coreinfra.cloud/hlv/dockerfiles/hlv-hugo-aws:latest
  tags:
    - kubernetes

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_DOWNLOAD_URL: "https://github.com/gohugoio/hugo/releases/download/v0.119.0/hugo_0.119.0_Linux-64bit.tar.gz"

stages:
  - lint
  - build
  - deploy

# Lint
lint:yaml:
  image: registry.coreinfra.cloud/hlv/dockerfiles/hlv-linter:latest
  stage: lint
  variables:
    YAMLLINT_CONFIG_FILE: "${CI_PROJECT_DIR}/.gitlab/yamllint.yaml"
  script:
    - "yamllint ."
  only:
    refs:
      - main
      - merge_requests
    changes:
      - "**/*.yaml"
      - "**/*.yml"
  allow_failure: false

# Jobs
.hugo:
  stage: deploy
  before_script:
    - aws sts get-caller-identity
    - hugo version
  script:
    - hugo -b $HUGO_BASE_URL
    - hugo deploy --target=${HUGO_DEPLOY_TARGET}

# Prod Build
hugo:s3:prod:
  extends: .hugo
  environment:
    name: prod
    url: https://nicholas.santiago.wtf
  variables:
    HUGO_BASE_URL: "https://nicholas.santiago.wtf"
    HUGO_DEPLOY_TARGET: production
  only:
    - main
